<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPBYMINW3264" ignored="0" name="Summation call test" tests="67" failures="18" timestamp="2020-03-12T18:16:17 MSK" time="0.122" errors="0">
  <testcase name="testCotangensFunctionWithTestNG" time="0.003" classname="com.epam.automation.testsTestNG.CatangensCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Ctg operation expected [1.7320508075688772] but found [0.4804727781564516]">
      <![CDATA[java.lang.AssertionError: Invalid result of Ctg operation expected [1.7320508075688772] but found [0.4804727781564516]
at com.epam.automation.testsTestNG.CatangensCalcTest.testCotangensFunctionWithTestNG(CatangensCalcTest.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testCotangensFunctionWithTestNG -->
  <testcase name="testCotangensFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.CatangensCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Ctg operation expected [1.0] but found [0.6557942026326724]">
      <![CDATA[java.lang.AssertionError: Invalid result of Ctg operation expected [1.0] but found [0.6557942026326724]
at com.epam.automation.testsTestNG.CatangensCalcTest.testCotangensFunctionWithTestNG(CatangensCalcTest.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testCotangensFunctionWithTestNG -->
  <testcase name="testCotangensFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.CatangensCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Ctg operation expected [0.0] but found [0.9998386139886326]">
      <![CDATA[java.lang.AssertionError: Invalid result of Ctg operation expected [0.0] but found [0.9998386139886326]
at com.epam.automation.testsTestNG.CatangensCalcTest.testCotangensFunctionWithTestNG(CatangensCalcTest.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testCotangensFunctionWithTestNG -->
  <testcase name="testIsNegativeValueWithPositiveParamTestNG" time="0.001" classname="com.epam.automation.testsTestNG.IsPositiveTest">
    <failure type="java.lang.AssertionError" message="Is positive operation has been failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Is positive operation has been failed expected [true] but found [false]
at com.epam.automation.testsTestNG.IsPositiveTest.testIsNegativeValueWithPositiveParamTestNG(IsPositiveTest.java:13)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testIsNegativeValueWithPositiveParamTestNG -->
  <testcase name="testIsNegativeValueWithPositiveParamTestNG" time="0.0" classname="com.epam.automation.testsTestNG.IsPositiveTest"/>
  <testcase name="testIsNegativeValueWithPositiveParamTestNG" time="0.0" classname="com.epam.automation.testsTestNG.IsPositiveTest"/>
  <testcase name="testMulOperationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.MulCalcTest"/>
  <testcase name="testMulOperationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.MulCalcTest"/>
  <testcase name="testMulOperationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.MulCalcTest"/>
  <testcase name="testMulOperationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.MulCalcTest"/>
  <testcase name="testMulOperationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.MulCalcTest"/>
  <testcase name="testMulOperationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.MulCalcTest"/>
  <testcase name="testMulOperationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.MulCalcTest"/>
  <testcase name="testMulOperationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.MulCalcTest"/>
  <testcase name="testMulOperationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.MulCalcTest"/>
  <testcase name="testMulOperationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.MulCalcTest"/>
  <testcase name="testPowerFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.PowCalcTest"/>
  <testcase name="testPowerFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.PowCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Pow operation expected [5.65685424949238] but found [4.0]">
      <![CDATA[java.lang.AssertionError: Invalid result of Pow operation expected [5.65685424949238] but found [4.0]
at com.epam.automation.testsTestNG.PowCalcTest.testPowerFunctionWithTestNG(PowCalcTest.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testPowerFunctionWithTestNG -->
  <testcase name="testPowerFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.PowCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Pow operation expected [4.12] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Invalid result of Pow operation expected [4.12] but found [1.0]
at com.epam.automation.testsTestNG.PowCalcTest.testPowerFunctionWithTestNG(PowCalcTest.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testPowerFunctionWithTestNG -->
  <testcase name="testPowerFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.PowCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Pow operation expected [-3.24] but found [3.24]">
      <![CDATA[java.lang.AssertionError: Invalid result of Pow operation expected [-3.24] but found [3.24]
at com.epam.automation.testsTestNG.PowCalcTest.testPowerFunctionWithTestNG(PowCalcTest.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testPowerFunctionWithTestNG -->
  <testcase name="testSubstractionWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SubCalcTest"/>
  <testcase name="testSubstractionWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SubCalcTest"/>
  <testcase name="testSubstractionWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SubCalcTest"/>
  <testcase name="testSubstractionWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SubCalcTest"/>
  <testcase name="testSubstractionWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SubCalcTest"/>
  <testcase name="testSubstractionWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SubCalcTest"/>
  <testcase name="testSubstractionWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SubCalcTest"/>
  <testcase name="testSubstractionWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SubCalcTest"/>
  <testcase name="testSubstractionWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SubCalcTest"/>
  <testcase name="testSubstractionWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SubCalcTest"/>
  <testcase name="testCosinesFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.CosinesCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Cos operation expected [1.0] but found [0.0]">
      <![CDATA[java.lang.AssertionError: Invalid result of Cos operation expected [1.0] but found [0.0]
at com.epam.automation.testsTestNG.CosinesCalcTest.testCosinesFunctionWithTestNG(CosinesCalcTest.java:15)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testCosinesFunctionWithTestNG -->
  <testcase name="testCosinesFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.CosinesCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Cos operation expected [0.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Invalid result of Cos operation expected [0.0] but found [1.0]
at com.epam.automation.testsTestNG.CosinesCalcTest.testCosinesFunctionWithTestNG(CosinesCalcTest.java:15)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testCosinesFunctionWithTestNG -->
  <testcase name="testCosinesFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.CosinesCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Cos operation expected [0.7071067811865476] but found [0.7071067811865475]">
      <![CDATA[java.lang.AssertionError: Invalid result of Cos operation expected [0.7071067811865476] but found [0.7071067811865475]
at com.epam.automation.testsTestNG.CosinesCalcTest.testCosinesFunctionWithTestNG(CosinesCalcTest.java:15)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testCosinesFunctionWithTestNG -->
  <testcase name="testDivOperationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.DivCalcTest">
    <failure type="java.lang.AssertionError" message="Incorrect result of division operation with double params expected [1.0] but found [Infinity]">
      <![CDATA[java.lang.AssertionError: Incorrect result of division operation with double params expected [1.0] but found [Infinity]
at com.epam.automation.testsTestNG.DivCalcTest.testDivOperationWithDoubleValuesTestNG(DivCalcTest.java:13)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testDivOperationWithDoubleValuesTestNG -->
  <testcase name="testDivOperationWithDoubleValuesTestNG" time="0.001" classname="com.epam.automation.testsTestNG.DivCalcTest"/>
  <testcase name="testDivOperationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.DivCalcTest"/>
  <testcase name="testDivOperationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.DivCalcTest"/>
  <testcase name="testDivOperationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.DivCalcTest"/>
  <testcase name="testDivOperationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.DivCalcTest"/>
  <testcase name="testDivOperationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.DivCalcTest"/>
  <testcase name="testDivOperationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.DivCalcTest">
    <failure type="java.lang.NumberFormatException" message="Attempt to divide by zero">
      <![CDATA[java.lang.NumberFormatException: Attempt to divide by zero
at com.epam.tat.module4.Calculator.div(Calculator.java:34)
at com.epam.automation.testsTestNG.DivCalcTest.testDivOperationWithLongValuesTestNG(DivCalcTest.java:30)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testDivOperationWithLongValuesTestNG -->
  <testcase name="testDivOperationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.DivCalcTest"/>
  <testcase name="testDivOperationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.DivCalcTest"/>
  <testcase name="testIsNegativeValueWithPositiveParamTestNG" time="0.0" classname="com.epam.automation.testsTestNG.IsNegativeTest"/>
  <testcase name="testIsNegativeValueWithPositiveParamTestNG" time="0.0" classname="com.epam.automation.testsTestNG.IsNegativeTest">
    <failure type="java.lang.AssertionError" message="Is negative operation has been failed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Is negative operation has been failed expected [false] but found [true]
at com.epam.automation.testsTestNG.IsNegativeTest.testIsNegativeValueWithPositiveParamTestNG(IsNegativeTest.java:13)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testIsNegativeValueWithPositiveParamTestNG -->
  <testcase name="testIsNegativeValueWithPositiveParamTestNG" time="0.0" classname="com.epam.automation.testsTestNG.IsNegativeTest"/>
  <testcase name="testSinesFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SinCalcTest"/>
  <testcase name="testSinesFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SinCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Sin operation expected [1.0] but found [-0.1411200080598672]">
      <![CDATA[java.lang.AssertionError: Invalid result of Sin operation expected [1.0] but found [-0.1411200080598672]
at com.epam.automation.testsTestNG.SinCalcTest.testSinesFunctionWithTestNG(SinCalcTest.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testSinesFunctionWithTestNG -->
  <testcase name="testSinesFunctionWithTestNG" time="0.001" classname="com.epam.automation.testsTestNG.SinCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Sin operation expected [1.0] but found [0.8414709848078965]">
      <![CDATA[java.lang.AssertionError: Invalid result of Sin operation expected [1.0] but found [0.8414709848078965]
at com.epam.automation.testsTestNG.SinCalcTest.testSinesFunctionWithTestNG(SinCalcTest.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testSinesFunctionWithTestNG -->
  <testcase name="testSquareRootFunctionWithTestNG" time="0.001" classname="com.epam.automation.testsTestNG.SqrtCalcTest"/>
  <testcase name="testSquareRootFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SqrtCalcTest"/>
  <testcase name="testSquareRootFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SqrtCalcTest"/>
  <testcase name="testSquareRootFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SqrtCalcTest"/>
  <testcase name="testSummationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SumCalcTest"/>
  <testcase name="testSummationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SumCalcTest"/>
  <testcase name="testSummationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SumCalcTest"/>
  <testcase name="testSummationWithDoubleValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SumCalcTest"/>
  <testcase name="testSummationWithDoubleValuesTestNG" time="0.001" classname="com.epam.automation.testsTestNG.SumCalcTest"/>
  <testcase name="testSummationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SumCalcTest"/>
  <testcase name="testSummationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SumCalcTest"/>
  <testcase name="testSummationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SumCalcTest"/>
  <testcase name="testSummationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SumCalcTest"/>
  <testcase name="testSummationWithLongValuesTestNG" time="0.0" classname="com.epam.automation.testsTestNG.SumCalcTest"/>
  <testcase name="testTangensFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.TangensCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Tg operation expected [0.0] but found [NaN]">
      <![CDATA[java.lang.AssertionError: Invalid result of Tg operation expected [0.0] but found [NaN]
at com.epam.automation.testsTestNG.TangensCalcTest.testTangensFunctionWithTestNG(TangensCalcTest.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testTangensFunctionWithTestNG -->
  <testcase name="testTangensFunctionWithTestNG" time="0.001" classname="com.epam.automation.testsTestNG.TangensCalcTest"/>
  <testcase name="testTangensFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.TangensCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Tg operation expected [1.7320508075688772] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Invalid result of Tg operation expected [1.7320508075688772] but found [1.0]
at com.epam.automation.testsTestNG.TangensCalcTest.testTangensFunctionWithTestNG(TangensCalcTest.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testTangensFunctionWithTestNG -->
  <testcase name="testTangensFunctionWithTestNG" time="0.0" classname="com.epam.automation.testsTestNG.TangensCalcTest">
    <failure type="java.lang.AssertionError" message="Invalid result of Tg operation expected [0.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Invalid result of Tg operation expected [0.0] but found [1.0]
at com.epam.automation.testsTestNG.TangensCalcTest.testTangensFunctionWithTestNG(TangensCalcTest.java:14)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testTangensFunctionWithTestNG -->
</testsuite> <!-- Summation call test -->
