<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPBYMINW3264" name="com.epam.automation.testsTestNG.IsNegativeTest" tests="3" failures="1" timestamp="2020-03-12T18:16:18 MSK" time="0.000" errors="0">
  <testcase name="testIsNegativeValueWithPositiveParamTestNG" time="0.000" classname="com.epam.automation.testsTestNG.IsNegativeTest"/>
  <system-out/>
  <testcase name="testIsNegativeValueWithPositiveParamTestNG" time="0.000" classname="com.epam.automation.testsTestNG.IsNegativeTest">
    <failure type="java.lang.AssertionError" message="Is negative operation has been failed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Is negative operation has been failed expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at com.epam.automation.testsTestNG.IsNegativeTest.testIsNegativeValueWithPositiveParamTestNG(IsNegativeTest.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testIsNegativeValueWithPositiveParamTestNG -->
  <system-out/>
  <testcase name="testIsNegativeValueWithPositiveParamTestNG" time="0.000" classname="com.epam.automation.testsTestNG.IsNegativeTest"/>
  <system-out/>
</testsuite> <!-- com.epam.automation.testsTestNG.IsNegativeTest -->
